# Generated by Django 2.0.10 on 2019-02-06 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190206_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='static/media/default.jpg', upload_to=''),
        ),
    ]
