# Generated by Django 2.0.10 on 2019-02-07 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190206_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='static/media/default.jpg', upload_to=''),
        ),
    ]
